(() => {
'use strict';
const $=id=>document.getElementById(id), wait=ms=>new Promise(r=>setTimeout(r,ms));
const A={SOCCER:'images/soccer-card.webp?v=20260904fix1',SHOOT:'images/shoot-card.webp',DEFENSE:'images/defense-card.webp',TACKLE:'images/tackle.webp?v=20260904tackle2',DRIBBLE:'images/dribble%20past-card.webp',YELLOW:'images/yellow-card.webp',COACH:'images/coach-guide.webp',PLAYER:'images/player-card.webp',GOALKEEPER:'images/goalkeeper-card.webp',BACK:'images/card-back.webp'};
const F={SOCCER:'images/soccer-card.png?v=20260904fix1',SHOOT:'images/shoot-card.png',DEFENSE:'images/defense-card.png',TACKLE:'images/tackle-card.png',DRIBBLE:'images/dribble%20past-card.png',YELLOW:'images/yellow-card.png'};
const L=['HOW TO WIN','YOUR TURN','SOCCER CARD','DEFENSE','DRIBBLE PAST','SHOOT','YELLOW','TACKLE','FINAL CHALLENGE'];
const S={lesson:0,step:0,typing:false,timer:0,text:'',cont:false,locked:false,strikes:[0,0,0,0],out:[false,false,false,false],final:0};
const image=(name,cls='')=>`<img class="${cls}" src="${A[name]}" alt="${name}" onerror="if(!this.dataset.f){this.dataset.f='1';this.src='${F[name]||A.BACK}'}">`;
const preloadImage=src=>new Promise(resolve=>{const i=new Image();let done=false;const fin=()=>{if(done)return;done=true;resolve()};i.onload=fin;i.onerror=fin;i.src=src;if(i.complete)fin()});
async function boot(){let n=0,vals=Object.values(A);await Promise.all(vals.map(src=>preloadImage(src).then(()=>{n++;$('loaderFill').style.width=Math.round(n/vals.length*100)+'%';$('loaderPct').textContent=Math.round(n/vals.length*100)+'%'})));await wait(160);$('loader').classList.add('done');$('app').hidden=false;setTimeout(()=>$('loader')?.remove(),320);lesson(0)}
function player(i){const names=['YOU','PLAYER 2','PLAYER 3','PLAYER 4'],st=S.strikes[i],cnt=[5,4,5,3][i];return `<div class="pName"><span>${names[i]}</span><span class="pTag">${S.out[i]?'OUT':'IN GAME'}</span></div><div class="pStats">SOCCER STRIKES ${st}/2</div><div class="strikes"><span class="strike ${st>0?'on':''}">⚽</span><span class="strike ${st>1?'danger':''}">⚽</span></div><div class="handFan">${Array.from({length:cnt},()=>'<i class="handBack"></i>').join('')}</div>`}
function renderPlayers(){['P0','P1','P2','P3'].forEach((id,i)=>{$(id).innerHTML=player(i);$(id).classList.toggle('out',S.out[i])})}
function renderProgress(){$('progress').innerHTML=L.map((_,i)=>`<i class="${i<S.lesson?'done':i===S.lesson?'on':''}"></i>`).join('');$('lessonName').textContent=`${S.lesson===8?'FINAL CHALLENGE':`LESSON ${S.lesson+1}/9`} — ${L[S.lesson]}`;$('lessonStatus').textContent=S.lesson===8?'No card hints. Make the calls.':'Coach guided'}
function coach(text,cont=false){clearTimeout(S.timer);S.text=text;S.cont=cont;S.typing=true;$('coachText').textContent='';$('coachContinue').hidden=true;let i=0;const tick=()=>{$('coachText').textContent=text.slice(0,++i);if(i<text.length)S.timer=setTimeout(tick,14);else{S.typing=false;$('coachContinue').hidden=!cont}};tick()}
function finishType(){clearTimeout(S.timer);$('coachText').textContent=S.text;S.typing=false;$('coachContinue').hidden=!S.cont}
function fx(text,kind='neutral',ms=900){const e=$('fx');e.textContent=text;e.className=`fx show ${kind}`;clearTimeout(fx.t);fx.t=setTimeout(()=>e.className='fx',ms)}
function clearFlow(){$('flow').innerHTML='<div class="flowEmpty">Actions will appear here.</div>'}
function arrow(){if($('flow').children.length&&!$('flow').querySelector('.flowEmpty')){const a=document.createElement('div');a.className='arrow';a.textContent='→';$('flow').appendChild(a)}}
function flowCard(name,text){$('flow').querySelector('.flowEmpty')?.remove();arrow();const n=document.createElement('div');n.className='flowCard';n.innerHTML=`${image(name)}<b>${text}</b>`;$('flow').appendChild(n);$('flow').scrollLeft=$('flow').scrollWidth}
function chip(text,kind=''){$('flow').querySelector('.flowEmpty')?.remove();arrow();const c=document.createElement('div');c.className=`chip ${kind}`;c.textContent=text;$('flow').appendChild(c);$('flow').scrollLeft=$('flow').scrollWidth}
function clearFocus(){document.querySelectorAll('.player').forEach(p=>p.classList.remove('focus'));$('drawPile').classList.remove('active')}
function focusPlayers(ids=[]){document.querySelectorAll('.player').forEach((p,i)=>p.classList.toggle('focus',ids.includes(i)))}
function clearTargets(){document.querySelectorAll('.player').forEach(p=>p.classList.remove('target','dim'))}
function targets(ids){document.querySelectorAll('.player').forEach((p,i)=>{p.classList.toggle('target',ids.includes(i));p.classList.toggle('dim',!ids.includes(i))})}
function hand(high=''){const cards=['DEFENSE','DRIBBLE','SHOOT','YELLOW','TACKLE'];$('hand').innerHTML=cards.map(n=>`<button class="cardBtn ${n===high?'highlight':''}" data-card="${n}" aria-label="Play ${n==='DRIBBLE'?'DRIBBLE PAST':n}">${image(n)}</button>`).join('');$('hand').querySelectorAll('.cardBtn').forEach(b=>b.onclick=()=>cardClick(b.dataset.card,b))}
function actions(arr=[]){$('actions').innerHTML='';arr.forEach(x=>{const b=document.createElement('button');b.className=`actionBtn ${x.kind||''} ${x.highlight?'highlight':''}`;b.textContent=x.label;b.onclick=x.go;$('actions').appendChild(b)})}
function reset(){clearTargets();clearFocus();clearFlow();renderPlayers();hand();actions([])}
function lesson(i){S.lesson=i;S.step=0;S.locked=false;document.body.classList.toggle('finalMode',i===8);renderProgress();reset();if(i===0){S.strikes[0]=0;S.out[0]=false;renderPlayers();focusPlayers([0]);coach('Draw Soccer twice and you’re out.',true);fx('SOCCER ×2 = OUT','warn',1400)}if(i===1){focusPlayers([0]);coach('Your turn.',true)}if(i===2){focusPlayers([0]);coach('Let’s see what a Soccer card does.',true)}if(i===3){S.strikes[0]=1;renderPlayers();focusPlayers([0]);coach('You already have one Soccer strike.',true)}if(i===4)coach('Want to know what’s coming?',true);if(i===5)coach('Make someone else take the risk.',true);if(i===6){focusPlayers([1]);coach('Watch this. PLAYER 2 is about to play SHOOT.',true)}if(i===7)coach('Need another card?',true);if(i===8){S.final=0;S.strikes[0]=1;S.out=[false,false,false,false];renderPlayers();focusPlayers([0]);coach('Now play a short round on your own.',true)}}
function next(){if(S.lesson<8)lesson(S.lesson+1)}
function advance(){const l=S.lesson,s=S.step++;$('coachContinue').hidden=true;if(l===0){if(s===0){S.strikes[0]=1;renderPlayers();focusPlayers([0]);fx('SOCCER 1 / 2 • DANGER','warn',1300);coach('One Soccer means danger.',true)}else if(s===1){S.strikes[0]=2;S.out[0]=true;renderPlayers();focusPlayers([0]);fx('SOCCER 2 / 2 • OUT','bad',1500);coach('The second Soccer knocks you out.',true)}else if(s===2){S.strikes[0]=0;S.out[0]=false;renderPlayers();clearFocus();coach('Last player standing wins.',true)}else next()}else if(l===1){if(s===0)coach('Every turn ends with your own draw.',true);else if(s===1){focusPlayers([0]);$('drawPile').classList.add('active');actions([{label:'DRAW 1 CARD',kind:'blue',highlight:true,go:()=>draw('normal')}]);coach('Draw a card.')}}else if(l===2&&s===0){focusPlayers([0]);$('drawPile').classList.add('active');actions([{label:'DRAW',kind:'blue',highlight:true,go:()=>draw('soccer1')}]);coach('Tap DRAW.')}else if(l===3&&s===0){focusPlayers([0]);$('drawPile').classList.add('active');actions([{label:'DRAW',kind:'blue',highlight:true,go:()=>draw('soccer2')}]);coach('Draw again.')}else if(l===4&&s===0){clearFocus();hand('DRIBBLE');coach('Play DRIBBLE PAST.')}else if(l===5&&s===0){hand('SHOOT');coach('Play SHOOT.')}else if(l===6&&s===0)opponentShoot();else if(l===7&&s===0){hand('TACKLE');coach('Use TACKLE.')}else if(l===8&&s===0)beginFinal()}
async function fly(from,to,src){if(!from||!to)return;const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),im=document.createElement('img');im.className='flying';im.src=src;im.style.left=a.left+'px';im.style.top=a.top+'px';im.style.width=Math.max(42,a.width)+'px';im.style.height=Math.max(58,a.height)+'px';document.body.appendChild(im);await wait(30);im.style.transform=`translate(${b.left+b.width/2-a.left-a.width/2}px,${b.top+b.height/2-a.top-a.height/2}px) scale(.8)`;im.style.opacity='.35';await wait(520);im.remove()}
async function playFromHand(name){const b=document.querySelector(`.cardBtn[data-card="${name}"]`);if(b)await fly(b,$('discardPile'),A[name])}
async function draw(mode){if(S.locked)return;S.locked=true;actions([]);$('drawPile').classList.remove('active');const tmp=document.createElement('div');tmp.style.cssText='position:absolute;left:50%;bottom:6%;width:60px;height:84px;transform:translateX(-50%)';$('table').appendChild(tmp);const n=mode.startsWith('soccer')?'SOCCER':'TACKLE';await fly($('drawPile'),tmp,A[n]);tmp.remove();flowCard(n,'YOU DRAW');if(mode==='normal'){chip('DRAW COMPLETE','good');fx('CARD DRAWN','good');coach('That draw ends your turn.',true);S.step=99}if(mode==='soccer1'){S.strikes[0]=1;renderPlayers();focusPlayers([0]);chip('SOCCER 1 / 2','warn');fx('FIRST SOCCER • DANGER','warn',1500);coach('Uh-oh. That’s a Soccer card.',true);S.step=10}if(mode==='soccer2'){focusPlayers([0]);chip('WOULD BE SOCCER 2 / 2','bad');fx('DANGER','bad',1300);hand('DEFENSE');coach('Play DEFENSE before this becomes your second Soccer.');S.step=20}S.locked=false}
function wrongLabel(card){if(S.lesson===3&&card==='SHOOT')return 'SHOOT DOES NOT SAVE YOU';if(S.lesson===4)return 'THAT DOES NOT PEEK';if(S.lesson===5)return 'NO FORCED DRAW';if(S.lesson===6)return 'ACTION STILL LIVE';if(S.lesson===7)return 'NO CARD STOLEN';if(S.lesson===8&&S.final===1)return `${card} DOES NOT STOP SOCCER`;if(S.lesson===8&&S.final===2)return `${card} DOES NOT LOOK AHEAD`;if(S.lesson===8&&S.final===3)return `${card} DOES NOT FORCE A DRAW`;if(S.lesson===8&&S.final===4)return `${card} DOES NOT CANCEL SHOOT`;if(S.lesson===8&&S.final===5)return `${card} DOES NOT STEAL`;return 'TRY AGAIN'}
function cardClick(n,b){if(S.locked)return;if(S.lesson===8)return finalCard(n,b);const need={3:'DEFENSE',4:'DRIBBLE',5:'SHOOT',6:'YELLOW',7:'TACKLE'}[S.lesson];if(n!==need)return wrong(b,{3:'SHOOT doesn’t protect you from Soccer.',4:'That won’t show the next cards.',5:'That won’t make another player draw.',6:'That won’t cancel their SHOOT.',7:'That won’t steal a card.'}[S.lesson]||'Try another card.',wrongLabel(n));if(n==='DEFENSE')defense();if(n==='DRIBBLE')dribble();if(n==='SHOOT')shoot();if(n==='YELLOW')yellow();if(n==='TACKLE')tackle()}
async function wrong(b,msg,label='TRY AGAIN'){if(S.locked)return;S.locked=true;b?.classList.add('wrong');setTimeout(()=>b?.classList.remove('wrong'),650);fx(label,'bad',1250);coach(msg);await wait(Math.max(1300,msg.length*14+500));fx('RESET • TRY AGAIN','neutral',700);coach('Try again.');await wait(650);S.locked=false}
async function defense(){S.locked=true;await playFromHand('DEFENSE');flowCard('DEFENSE','YOU PLAY DEFENSE');await wait(220);chip('SOCCER BLOCKED','good');fx('SAFE','good',1400);await wait(350);await fly($('discardPile'),$('drawPile'),A.SOCCER);chip('SOCCER → BACK INTO DECK','good');S.strikes[0]=1;renderPlayers();focusPlayers([0]);coach('Nice. DEFENSE keeps you in the game.',true);S.step=31;S.locked=false}
function showTop3(){fx('NEXT 3 CARDS','neutral',1200);$('top3').innerHTML=[['YELLOW',1],['SOCCER',2],['TACKLE',3]].map(([n,i])=>`<div class="preview"><span class="num">${i}</span>${image(n)}</div>`).join('');$('top3Modal').classList.add('show')}
async function dribble(){S.locked=true;await playFromHand('DRIBBLE');flowCard('DRIBBLE','YOU PLAY');await wait(180);showTop3();coach('Now you know the next three cards.');S.locked=false}
$('closeTop3').onclick=()=>{$('top3Modal').classList.remove('show');if(S.lesson===8&&S.final===3){coach('Your move.');return}coach('You only look. You don’t change the order.',true);S.step=99};
async function shoot(){S.locked=true;await playFromHand('SHOOT');flowCard('SHOOT','YOU PLAY SHOOT');targets([1,2,3]);$('targetModal').classList.add('show');coach('Choose another player.');S.locked=false}
async function tackle(){S.locked=true;await playFromHand('TACKLE');flowCard('TACKLE','YOU PLAY TACKLE');targets([1,2,3]);$('targetModal').classList.add('show');coach('Choose someone to steal from.');S.locked=false}
async function forcedDraw(i){await fly($('drawPile'),$('P'+i),A.BACK);chip(`PLAYER ${i+1} DRAWS 1`,'good')}
async function steal(i){await fly($('P'+i),$('hand'),A.BACK);chip('CARD ADDED TO YOUR HAND','good')}
async function pickTarget(i){$('targetModal').classList.remove('show');clearTargets();focusPlayers([i]);if(S.lesson===5){chip(`TARGET → PLAYER ${i+1}`,'warn');fx('SHOOT → TARGET','neutral',1200);await wait(250);chip('TARGET DRAWS 1 NOW','good');await forcedDraw(i);coach('SHOOT makes that player draw one card right away.',true);S.step=99}else if(S.lesson===7){chip(`TARGET → PLAYER ${i+1}`,'warn');fx('TARGET → CARD STOLEN','good',1200);await steal(i);coach('TACKLE steals one random card from another player.',true);S.step=99}else if(S.lesson===8&&S.final===3){chip(`SHOOT TARGET → PLAYER ${i+1}`,'good');fx('SHOOT → TARGET','neutral',900);await forcedDraw(i);S.final=4;await wait(250);finalOpponentShoot()}else if(S.lesson===8&&S.final===5){chip(`TACKLE TARGET → PLAYER ${i+1}`,'good');fx('CARD STOLEN','good',1000);await steal(i);S.final=6;finishFinal()}}
document.querySelectorAll('#targetModal .targetBtn').forEach(b=>b.onclick=()=>pickTarget(Number(b.dataset.player)));
async function opponentShoot(){S.locked=true;clearFocus();focusPlayers([1]);flowCard('SHOOT','PLAYER 2 PLAYS SHOOT');fx('OPPONENT PLAYS SHOOT','bad',1200);await wait(450);focusPlayers([0]);S.step=60;coach('They’re coming after you.',true);S.locked=false}
async function yellow(){S.locked=true;await playFromHand('YELLOW');flowCard('YELLOW','YOU PLAY YELLOW');await wait(260);chip('🚫 CANCELED','good');fx('NOPE! • CANCELED','good',1500);clearFocus();coach('YELLOW cancels the action.',true);S.step=99;S.locked=false}
function beginFinal(){clearFlow();clearFocus();focusPlayers([0]);S.final=0;hand();$('drawPile').classList.add('active');actions([{label:'DRAW',kind:'blue',go:finalDraw}]);coach('Your move.')}
async function finalDraw(){if(S.final!==0||S.locked)return;S.locked=true;S.final=1;actions([]);$('drawPile').classList.remove('active');const tmp=document.createElement('div');tmp.style.cssText='position:absolute;left:50%;bottom:6%;width:60px;height:84px;transform:translateX(-50%)';$('table').appendChild(tmp);await fly($('drawPile'),tmp,A.SOCCER);tmp.remove();flowCard('SOCCER','YOU DRAW');chip('WOULD BE SOCCER 2 / 2','bad');fx('DANGER','bad',1300);focusPlayers([0]);hand();coach('Your move.');S.locked=false}
async function finalCard(n,b){if(S.locked)return;if(S.final===1){if(n!=='DEFENSE')return wrong(b,'That won’t stop a Soccer card.',wrongLabel(n));S.locked=true;await playFromHand('DEFENSE');flowCard('DEFENSE','YOU PLAY');chip('SAFE','good');fx('SAFE','good',1000);await fly($('discardPile'),$('drawPile'),A.SOCCER);chip('SOCCER → BACK INTO DECK','good');S.final=2;coach('Good. Keep playing.');S.locked=false}else if(S.final===2){if(n!=='DRIBBLE')return wrong(b,'That card doesn’t help you look ahead.',wrongLabel(n));S.locked=true;await playFromHand('DRIBBLE');flowCard('DRIBBLE','YOU PLAY');S.final=3;showTop3();coach('You checked the next three cards.');S.locked=false}else if(S.final===3){if(n!=='SHOOT')return wrong(b,'That move does not make another player draw.',wrongLabel(n));await shoot()}else if(S.final===4){if(n!=='YELLOW')return wrong(b,'That SHOOT is still coming at you.',wrongLabel(n));S.locked=true;await playFromHand('YELLOW');flowCard('YELLOW','YOU PLAY');chip('🚫 CANCELED','good');fx('CANCELED','good',1100);S.final=5;coach('Your move.');S.locked=false}else if(S.final===5){if(n!=='TACKLE')return wrong(b,'That doesn’t steal a card.',wrongLabel(n));await tackle()}}
async function finalOpponentShoot(){clearFocus();focusPlayers([2]);flowCard('SHOOT','PLAYER 3 SHOOTS YOU');fx('OPPONENT SHOOT','bad',1100);await wait(350);focusPlayers([0]);coach('They’re coming after you. Stop the action.')}
function finishFinal(){clearFocus();focusPlayers([0]);fx('CHALLENGE COMPLETE','good',1700);chip('YOU SURVIVED THE ROUND','good');coach('You’ve got it.',true);S.step=200}
function coachTap(){if(S.locked)return;if(S.typing){finishType();return}if(S.lesson===8&&S.step===200){S.step=201;coach('You’re ready to play.');actions([{label:'BACK TO MODES',kind:'green',go:()=>location.href='index.html'}]);return}if($('coachContinue').hidden)return;if(S.step===99){next();return}if(S.lesson===2&&S.step===10){coach('This is your first one, so you’re still in the game.',true);S.step=99;return}if(S.lesson===3&&S.step===31){coach('Put the Soccer card back below the top of the deck.',true);S.step=99;return}if(S.lesson===6&&S.step===60){S.step=61;coach('You can stop that action.',true);return}if(S.lesson===6&&S.step===61){S.step=62;hand('YELLOW');coach('Play YELLOW.');return}advance()}
$('drawPile').onclick=()=>{if(!$('drawPile').classList.contains('active'))return;const b=$('actions').querySelector('button');if(b)b.click()};
$('coachBubble').onclick=coachTap;$('coachBubble').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();coachTap()}};
$('ruleBtn').onclick=()=>$('rulebookModal').classList.add('show');$('closeRulebook').onclick=()=>$('rulebookModal').classList.remove('show');$('coursesBtn').onclick=()=>$('coursesModal').classList.add('show');$('closeCourses').onclick=()=>$('coursesModal').classList.remove('show');
$('courses').innerHTML=L.map((n,i)=>`<button class="targetBtn" data-lesson="${i}">${i===8?'FINAL':i+1}. ${n}</button>`).join('');$('courses').querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{$('coursesModal').classList.remove('show');lesson(Number(b.dataset.lesson))});
renderPlayers();renderProgress();boot();
})();