(()=>{
'use strict';
const CARD_IMG={SHOOT:'images/shoot-card.webp',DEFENSE:'images/defense-card.webp',TACKLE:'images/tackle.webp?v=20260904tackle2',DRIBBLE:'images/dribble%20past-card.webp',YELLOW:'images/yellow-card.webp'};
const FULL_DECK=[...Array(10).fill('SHOOT'),...Array(12).fill('DEFENSE'),...Array(10).fill('TACKLE'),...Array(10).fill('DRIBBLE'),...Array(9).fill('YELLOW')];
const BLUE=['B1','B2','BKG'], GREEN=['G1','G2','GKG'];
const DEF_ORDER={blue:['B1','B2','BKG'],green:['G1','G2','GKG']};
const state={hands:{},score:{blue:0,green:0},ball:null,phase:'trade',selectedHand:'B1',tradePick:null,time:600,timer:null,flow:[],busy:false,timeExpired:false,attack:null,counterMissing:{blue:null,green:null},ended:false};
const $=id=>document.getElementById(id); const teamOf=id=>id[0]==='B'?'blue':'green'; const other=t=>t==='blue'?'green':'blue'; const isGK=id=>id.includes('KG');
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function log(s){const d=document.createElement('div');d.textContent=s;$('log').prepend(d)}
function setNotice(s,type=''){const n=$('notice');n.textContent=s;n.className='notice'+(type?' '+type:'')}
function addFlow(s,type=''){state.flow.push({s,type});state.flow=state.flow.slice(-9);$('flow').innerHTML=state.flow.map(x=>`<span class="chip ${x.type}">${x.s}</span>`).join('')}
function fmt(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`}
function updateClock(){$('clock').textContent=fmt(state.time);if(state.time<=60)$('clockLabel').textContent='FINAL MINUTE'}
function deal(){const d=shuffle(FULL_DECK);const seats=['B1','G1','B2','G2','BKG','GKG'];seats.forEach(x=>state.hands[x]=[]);d.forEach((c,i)=>state.hands[seats[i%seats.length]].push(c));render();startTimer();log('All 51 Action Cards dealt. 10:00 starts now.');}
function startTimer(){clearInterval(state.timer);state.timer=setInterval(()=>{if(state.ended)return;state.time=Math.max(0,state.time-1);updateClock();if(state.time===0){state.timeExpired=true;if(!state.attack&&!state.busy)finishMatch('FULL TIME')}} ,1000)}
function renderPlayers(){[...BLUE,...GREEN].forEach(id=>{const p=$(id);p.querySelector('.handCount').textContent=`${state.hands[id]?.length||0} CARDS`;p.classList.toggle('hasBall',state.ball===id);p.classList.toggle('active',state.ball===id);p.classList.toggle('missing',state.counterMissing[teamOf(id)]===id && state.attack && state.attack.defTeam===teamOf(id));p.classList.toggle('beaten',!!(state.attack?.beaten||[]).includes(id))});$('blueScore').textContent=state.score.blue;$('greenScore').textContent=state.score.green}
function renderTabs(){if(state.phase==='trade'||(state.phase==='play'&&teamOf(state.ball||'G1')==='blue')){$('handTabs').innerHTML=BLUE.map(id=>`<button class="tab ${state.selectedHand===id?'on':''}" data-tab="${id}">${id==='BKG'?'BLUE GK':id.replace('B','BLUE ')}</button>`).join('');[...$('handTabs').children].forEach(b=>b.onclick=()=>{state.selectedHand=b.dataset.tab;state.tradePick=null;render()})}else $('handTabs').innerHTML=''}
function cardButton(card,idx,id,enabled=true){return `<button class="card" data-card="${card}" data-idx="${idx}" data-owner="${id}" ${enabled?'':'disabled'}><img src="${CARD_IMG[card]}" alt="${card}"><span class="cardTag">${card}</span></button>`}
function renderHand(){const id=state.selectedHand;const h=state.hands[id]||[];let enabled=true;if(state.phase==='play')enabled=(state.ball===id&&!state.busy&&!state.attack);if(state.phase==='ai')enabled=false;$('cards').innerHTML=h.map((c,i)=>cardButton(c,i,id,enabled||state.phase==='trade')).join('');[...$('cards').querySelectorAll('.card')].forEach(b=>{if(state.phase==='trade')b.onclick=()=>tradeSelect(b);else if(state.phase==='play')b.onclick=()=>playCard(b.dataset.card,b.dataset.owner,Number(b.dataset.idx))})}
function renderActions(){const a=$('actions');a.innerHTML='';if(state.phase==='trade'){a.innerHTML='<button class="action" id="readyBtn">LOCK TEAM & PLAY RPS</button><button class="action dark" id="autoTrade">AUTO BALANCE</button>'; $('readyBtn').onclick=lockTrade;$('autoTrade').onclick=autoBalance;return}
if(state.phase==='play'&&!state.busy&&!state.attack&&teamOf(state.ball)==='blue'){const holder=state.ball;BLUE.filter(x=>x!==holder).forEach(id=>{const b=document.createElement('button');b.className='action blue';b.textContent=`PASS → ${id==='BKG'?'GK':id.replace('B','P')}`;b.onclick=()=>userPass(holder,id);a.appendChild(b)});const end=document.createElement('button');end.className='action dark';end.textContent='END MATCH (TEST)';end.onclick=()=>finishMatch('TEST END');a.appendChild(end)}else if(state.phase==='ai'||state.busy||state.attack){a.innerHTML='<button class="action dark" disabled>WAIT FOR PLAY</button>'}else if(state.phase==='ended'){a.innerHTML='<button class="action" onclick="location.reload()">NEW MATCH</button>'}}
function render(){renderPlayers();renderTabs();renderHand();renderActions();updateClock();checkDeadGame()}
function tradeSelect(btn){const pick={owner:btn.dataset.owner,idx:Number(btn.dataset.idx),card:btn.dataset.card};if(!state.tradePick){state.tradePick=pick;btn.classList.add('sel');setNotice(`Selected ${pick.card} from ${name(pick.owner)}. Now choose a card from a different teammate.`);return}if(state.tradePick.owner===pick.owner){state.tradePick=pick;render();setNotice('Pick the second card from a different teammate.','warn');return}const a=state.tradePick,b=pick;[state.hands[a.owner][a.idx],state.hands[b.owner][b.idx]]=[state.hands[b.owner][b.idx],state.hands[a.owner][a.idx]];log(`Trade: ${name(a.owner)} swapped ${a.card} for ${b.card} with ${name(b.owner)}.`);state.tradePick=null;render();setNotice('Trade complete. Keep swapping or lock your team.')}
function autoBalance(){const sizes={B1:state.hands.B1.length,B2:state.hands.B2.length,BKG:state.hands.BKG.length};const cards=BLUE.flatMap(id=>state.hands[id]);const gk=[];for(let i=cards.length-1;i>=0&&gk.length<sizes.BKG;i--){if(cards[i]==='DEFENSE')gk.push(cards.splice(i,1)[0])}while(gk.length<sizes.BKG&&cards.length)gk.push(cards.shift());state.hands.BKG=gk;state.hands.B1=cards.splice(0,sizes.B1);state.hands.B2=cards.splice(0,sizes.B2);log('Auto-balance moved DEFENSE toward your Goalkeeper while preserving hand sizes.');render();setNotice('Auto-balance complete. You can still make 1-for-1 trades.')}
function lockTrade(){state.tradePick=null;state.phase='rps';$('phaseTitle').textContent='FIRST POSSESSION';$('phaseHelp').textContent='Rock-Paper-Scissors decides who attacks first.';showRPS('Opening possession',res=>{if(res==='win'){state.ball='B1';startBlueTurn('You won the opening RPS. BLUE 1 starts with Soccer.')}else{state.ball='G1';startAITurn('AI won the opening RPS. GREEN 1 starts with Soccer.')}})}
function showRPS(title,cb){showModal(title,'Choose Rock, Paper, or Scissors.',[['✊ ROCK','rock'],['✋ PAPER','paper'],['✌️ SCISSORS','scissors']],choice=>{const ai=['rock','paper','scissors'][Math.floor(Math.random()*3)];const win=(choice==='rock'&&ai==='scissors')||(choice==='paper'&&ai==='rock')||(choice==='scissors'&&ai==='paper');const tie=choice===ai;log(`RPS: You ${choice.toUpperCase()} · AI ${ai.toUpperCase()}`);if(tie){setTimeout(()=>showRPS(title,cb),250)}else cb(win?'win':'lose')})}
function name(id){return id==='BKG'?'BLUE GK':id==='GKG'?'AI GK':id.replace('B','BLUE ').replace('G','GREEN ')}
function has(id,c){return state.hands[id]?.includes(c)}
function removeCard(id,c){const i=state.hands[id].indexOf(c);if(i<0)return false;state.hands[id].splice(i,1);return true}
function randomDiscard(id){if(!state.hands[id].length)return null;const i=Math.floor(Math.random()*state.hands[id].length);return state.hands[id].splice(i,1)[0]}
function startBlueTurn(msg){state.phase='play';state.busy=false;state.attack=null;state.selectedHand=BLUE.includes(state.ball)?state.ball:'B1';$('phaseTitle').textContent='YOUR POSSESSION';$('phaseHelp').textContent='Pass freely, play SHOOT, or hold your cards. AI can attempt TACKLE even before a pass.';setNotice(msg);addFlow('BLUE POSSESSION','good');render();offerTrackBackIfNeeded('green',()=>setTimeout(aiOpenTackle,450))}
function startAITurn(msg){state.phase='ai';state.busy=true;state.attack=null;$('phaseTitle').textContent='AI POSSESSION';$('phaseHelp').textContent='You may get a TACKLE chance before the AI passes or shoots.';setNotice(msg);addFlow('AI POSSESSION','bad');render();offerTrackBackIfNeeded('blue',()=>setTimeout(userOpenTackleWindow,700))}
function aiOpenTackle(){if(state.ended||state.phase!=='play'||state.busy||state.attack||teamOf(state.ball)!=='blue')return;const d=firstDefender('green');if(d&&!isGK(d)&&has(d,'TACKLE')&&Math.random()<.32){removeCard(d,'TACKLE');addFlow(`${name(d)} TACKLE`,'bad');log(`${name(d)} tries a standing TACKLE before your move.`);counterPrompt('AI TACKLE',d,()=>{gainBall(d,false);startAITurn(`${name(d)} stole the Soccer.`)},()=>{state.counterMissing.green=d;setNotice(`You beat ${name(d)}. That defensive line is now behind the play.`);render()})}}
function counterPrompt(title,defender,onLose,onBeat){const holder=state.ball;const opts=[];if(has(holder,'DRIBBLE'))opts.push(['DRIBBLE PAST','dribble']);if(has(holder,'YELLOW'))opts.push(['YELLOW','yellow']);opts.push(['LOSE POSSESSION','lose']);showModal(title,'TACKLE can steal the Soccer. DRIBBLE gets past the defender, or YELLOW cancels the TACKLE.',opts,val=>{if(val==='dribble'){removeCard(holder,'DRIBBLE');addFlow('DRIBBLE PAST','good');onBeat()}else if(val==='yellow'){removeCard(holder,'YELLOW');addFlow('YELLOW → TACKLE CANCELED','good');if(has(defender,'YELLOW')&&Math.random()<.3){removeCard(defender,'YELLOW');addFlow('YELLOW → YELLOW','bad');log('AI counters your YELLOW with another YELLOW.');onLose()}else onBeat()}else onLose();render()})}
function userPass(from,to){if(state.busy||state.attack)return;state.busy=true;addFlow(`${name(from)} PASS → ${name(to)}`,'good');const d=firstDefender('green');if(d&&!isGK(d)&&has(d,'TACKLE')&&Math.random()<.5){removeCard(d,'TACKLE');addFlow(`${name(d)} TACKLE PASS`,'bad');counterPrompt('PASS UNDER PRESSURE',d,()=>{gainBall(d,false);startAITurn(`${name(d)} intercepted the pass.`)},()=>{state.counterMissing.green=d;state.ball=to;state.busy=false;state.selectedHand=to;setNotice(`Pass survives the tackle. ${name(d)} is behind the play and ${name(to)} has Soccer.`);render();setTimeout(aiOpenTackle,400)})}else{state.ball=to;state.busy=false;state.selectedHand=to;setNotice(`Pass complete. ${name(to)} has Soccer.`);render();setTimeout(aiOpenTackle,400)}}
function playCard(card,owner,idx){if(state.phase!=='play'||state.busy||state.attack||owner!==state.ball)return;if(card==='SHOOT'){removeCard(owner,'SHOOT');beginAttack(owner,'green')}else if(card==='YELLOW'){setNotice('YELLOW is a reaction card. Use it when an opponent plays a cancellable Action.','warn')}else if(card==='DRIBBLE'){setNotice('DRIBBLE PAST is used after a defender plays DEFENSE or TACKLE.','warn')}else if(card==='TACKLE'||card==='DEFENSE'){setNotice(`${card} is used while defending, not while your team has the ball.`,'warn')}render()}
function firstDefender(team){const order=DEF_ORDER[team];const missing=state.counterMissing[team];for(const id of order){if(id===missing)continue;return id}return order[order.length-1]}
function beginAttack(shooter,defTeam){state.attack={shooter,atkTeam:teamOf(shooter),defTeam,index:0,beaten:[],current:null};state.busy=true;addFlow(`${name(shooter)} SHOOT`,teamOf(shooter)==='blue'?'good':'bad');log(`${name(shooter)} shoots.`);setNotice(`${name(shooter)} attacks the first defensive line.`);render();setTimeout(()=>defendStep(),450)}
function currentDefender(){const order=DEF_ORDER[state.attack.defTeam];while(state.attack.index<order.length&&state.counterMissing[state.attack.defTeam]===order[state.attack.index])state.attack.index++;return order[state.attack.index]||order[order.length-1]}
function defendStep(){if(!state.attack)return;const d=currentDefender();state.attack.current=d;if(isGK(d)){goalkeeperStage(d);return}if(state.attack.defTeam==='green')aiDefender(d);else userDefender(d)}
function aiDefender(d){const choices=[];if(has(d,'TACKLE'))choices.push('TACKLE');if(has(d,'DEFENSE'))choices.push('DEFENSE');if(!choices.length){addFlow(`${name(d)} NO DEFENSE`);state.attack.beaten.push(d);state.attack.index++;render();setTimeout(defendStep,350);return}const card=choices[Math.floor(Math.random()*choices.length)];removeCard(d,card);addFlow(`${name(d)} ${card}`,'bad');const shooter=state.attack.shooter;const opts=[];if(has(shooter,'DRIBBLE'))opts.push(['DRIBBLE PAST','dribble']);if(card==='TACKLE'&&has(shooter,'YELLOW'))opts.push(['YELLOW','yellow']);opts.push([card==='DEFENSE'?'LET DEFENSE STOP SHOT':'LOSE SOCCER','lose']);showModal(`${name(d)} PLAYS ${card}`,card==='DEFENSE'?'DEFENSE cannot be canceled by YELLOW. DRIBBLE PAST gets through this defender.':'TACKLE stops the shot and steals Soccer unless you beat or cancel it.',opts,val=>{if(val==='dribble'){removeCard(shooter,'DRIBBLE');addFlow('DRIBBLE PAST','good');state.attack.beaten.push(d);maybeAIChase(d)}else if(val==='yellow'){removeCard(shooter,'YELLOW');addFlow('YELLOW → TACKLE CANCELED','good');if(has(d,'YELLOW')&&Math.random()<.28){removeCard(d,'YELLOW');addFlow('YELLOW → YELLOW','bad');finishDefenseWin(d,true)}else{state.attack.beaten.push(d);state.attack.index++;render();setTimeout(defendStep,300)}}else finishDefenseWin(d,card==='TACKLE');render()})}
function maybeAIChase(d){if(state.hands[d].length>=2&&Math.random()<.38&&(has(d,'DEFENSE')||has(d,'TACKLE'))){const cost=randomDiscard(d);let card=has(d,'TACKLE')&&Math.random()<.5?'TACKLE':'DEFENSE';if(!has(d,card))card=has(d,'DEFENSE')?'DEFENSE':'TACKLE';removeCard(d,card);addFlow(`${name(d)} DISCARD ${cost} + CHASE ${card}`,'bad');log(`${name(d)} spends one extra card to track back after being dribbled.`);const shooter=state.attack.shooter;const opts=[];if(has(shooter,'DRIBBLE'))opts.push(['DRIBBLE AGAIN','dribble']);if(card==='TACKLE'&&has(shooter,'YELLOW'))opts.push(['YELLOW','yellow']);opts.push(['ATTACK STOPS','lose']);showModal('TRACK BACK',`${name(d)} discarded ${cost} to recover position and defend again.`,opts,val=>{if(val==='dribble'){removeCard(shooter,'DRIBBLE');addFlow('DRIBBLE PAST','good');state.attack.index++;render();setTimeout(defendStep,300)}else if(val==='yellow'){removeCard(shooter,'YELLOW');addFlow('YELLOW → TACKLE CANCELED','good');state.attack.index++;render();setTimeout(defendStep,300)}else finishDefenseWin(d,card==='TACKLE')})}else{state.attack.index++;render();setTimeout(defendStep,300)}}
function userDefender(d){const opts=[];if(has(d,'DEFENSE'))opts.push(['DEFENSE','defense']);if(has(d,'TACKLE'))opts.push(['TACKLE','tackle']);opts.push(['LET HIM THROUGH','skip']);showModal(`${name(d)} — DEFEND`,`${name(state.attack.shooter)} is shooting. Choose this defender's response.`,opts,val=>{if(val==='skip'){state.attack.beaten.push(d);state.attack.index++;render();setTimeout(defendStep,300);return}const card=val.toUpperCase();removeCard(d,card);addFlow(`${name(d)} ${card}`,'good');aiAttackResponse(d,card)})}
function aiAttackResponse(d,card){const shooter=state.attack.shooter;const canDribble=has(shooter,'DRIBBLE');const canYellow=card==='TACKLE'&&has(shooter,'YELLOW');let response='lose';if(canDribble&&Math.random()<.65)response='dribble';else if(canYellow&&Math.random()<.6)response='yellow';if(response==='dribble'){removeCard(shooter,'DRIBBLE');addFlow('AI DRIBBLE PAST','bad');state.attack.beaten.push(d);askUserChase(d)}else if(response==='yellow'){removeCard(shooter,'YELLOW');addFlow('AI YELLOW → TACKLE','bad');if(has(d,'YELLOW')){showModal('YELLOW CHAIN','AI canceled your TACKLE with YELLOW. Counter with your own YELLOW?',[['PLAY YELLOW','yes'],['LET IT GO','no']],v=>{if(v==='yes'){removeCard(d,'YELLOW');addFlow('YELLOW → YELLOW','good');finishDefenseWin(d,true)}else{state.attack.beaten.push(d);state.attack.index++;render();setTimeout(defendStep,300)}})}else{state.attack.beaten.push(d);state.attack.index++;render();setTimeout(defendStep,300)}}else finishDefenseWin(d,card==='TACKLE')}
function askUserChase(d){if(state.hands[d].length<2||(!has(d,'DEFENSE')&&!has(d,'TACKLE'))){state.attack.index++;render();setTimeout(defendStep,300);return}showModal('YOU WERE DRIBBLED',`${name(d)} was beaten. Discard 1 extra card to track back and defend again?`,[['TRACK BACK','yes'],['LET NEXT LINE DEFEND','no']],v=>{if(v==='no'){state.attack.index++;render();setTimeout(defendStep,300);return}showDiscardForChase(d)})}
function showDiscardForChase(d){const cards=[...new Set(state.hands[d])];showModal('DISCARD 1 FOR TRACK BACK','Choose one card to spend as stamina.',cards.map(c=>[`DISCARD ${c}`,c]),cost=>{removeCard(d,cost);addFlow(`${name(d)} DISCARD ${cost}`,'good');const opts=[];if(has(d,'DEFENSE'))opts.push(['DEFENSE','DEFENSE']);if(has(d,'TACKLE'))opts.push(['TACKLE','TACKLE']);if(!opts.length){state.attack.index++;render();setTimeout(defendStep,300);return}showModal('DEFEND AGAIN','Now play the defensive card.',opts,card=>{removeCard(d,card);addFlow(`${name(d)} CHASE ${card}`,'good');aiAttackResponse(d,card)})})}
function finishDefenseWin(d,tackle){const attacking=state.attack;const wasShoot=true;state.attack=null;state.busy=false;state.counterMissing[attacking.defTeam]=null;gainBall(d,wasShoot&&tackle);if(tackle&&wasShoot)state.counterMissing[attacking.atkTeam]=attacking.shooter;addFlow(tackle?'TACKLE WINS SOCCER':'DEFENSE WINS SOCCER',teamOf(d)==='blue'?'good':'bad');if(teamOf(d)==='blue')startBlueTurn(`${name(d)} stopped the attack and has Soccer.`);else startAITurn(`${name(d)} stopped the attack and has Soccer.`);afterResolution()}
function goalkeeperStage(gk){const atk=state.attack;const shooter=atk.shooter;if(!has(gk,'DEFENSE')){scoreGoal(atk.atkTeam,shooter);return}removeCard(gk,'DEFENSE');addFlow(`${name(gk)} DEFENSE` ,teamOf(gk)==='blue'?'good':'bad');if(atk.atkTeam==='blue'){showRPS('GOALKEEPER DUEL',res=>{if(res==='win')scoreGoal('blue',shooter);else goalkeeperSave(gk)})}else{showRPS('GOALKEEPER DUEL',res=>{if(res==='win')goalkeeperSave(gk);else scoreGoal('green',shooter)})}}
function goalkeeperSave(gk){const defendedTeam=teamOf(gk);state.attack=null;state.busy=false;state.counterMissing[defendedTeam]=null;gainBall(gk,false);addFlow('SAVE','good');if(teamOf(gk)==='blue')startBlueTurn(`${name(gk)} saves it and keeps Soccer. You can pass to any teammate.`);else startAITurn(`${name(gk)} saves it and AI takes possession.`);afterResolution()}
function scoreGoal(team,shooter){state.score[team]++;state.attack=null;state.busy=false;addFlow(`${team.toUpperCase()} GOAL +1`,team==='blue'?'good':'bad');log(`${name(shooter)} scores for ${team.toUpperCase()}!`);const concede=other(team);state.counterMissing.blue=null;state.counterMissing.green=null;state.ball=concede==='blue'?'B1':'G1';render();if(concede==='blue')startBlueTurn('GOAL. BLUE restarts with Soccer.');else startAITurn('GOAL. AI GREEN restarts with Soccer.');afterResolution()}
function gainBall(id){state.ball=id;render()}
function userOpenTackleWindow(){if(state.ended||state.phase!=='ai'||state.attack)return;const d=firstDefender('blue');if(!d||isGK(d)||!has(d,'TACKLE')){setTimeout(aiChooseAction,500);return}showModal('TACKLE WINDOW',`${name(d)} can attempt TACKLE before AI makes its move.`,[['PLAY TACKLE','yes'],['HOLD POSITION','no']],v=>{if(v==='yes'){removeCard(d,'TACKLE');addFlow(`${name(d)} TACKLE`,'good');const holder=state.ball;if(has(holder,'DRIBBLE')&&Math.random()<.55){removeCard(holder,'DRIBBLE');addFlow('AI DRIBBLE PAST','bad');state.counterMissing.blue=d;log(`${name(d)} was beaten before the AI attack.`);setTimeout(aiChooseAction,350)}else if(has(holder,'YELLOW')&&Math.random()<.4){removeCard(holder,'YELLOW');addFlow('AI YELLOW → TACKLE','bad');setTimeout(aiChooseAction,350)}else{state.ball=d;state.phase='play';state.busy=false;state.selectedHand=d;setNotice(`${name(d)} wins Soccer with TACKLE.`);addFlow('TACKLE WINS SOCCER','good');render();afterResolution()}}else aiChooseAction()})}
function aiChooseAction(){if(state.ended||teamOf(state.ball)!=='green')return;const holder=state.ball;const mates=GREEN.filter(x=>x!==holder);if(!has(holder,'SHOOT')){const shooter=GREEN.find(x=>has(x,'SHOOT'));if(shooter){aiPass(holder,shooter);return}setNotice('AI has no SHOOT anywhere. It holds possession but cannot create a legal shot.','warn');state.busy=false;render();checkDeadGame();return}if(Math.random()<.26&&mates.length){aiPass(holder,mates[Math.floor(Math.random()*mates.length)]);return}beginAttack(holder,'blue')}
function aiPass(from,to){addFlow(`${name(from)} PASS → ${name(to)}`,'bad');const d=firstDefender('blue');if(d&&!isGK(d)&&has(d,'TACKLE')){showModal('PASS TO INTERCEPT',`${name(d)} can TACKLE this pass.`,[['TACKLE','yes'],['LET PASS GO','no']],v=>{if(v==='yes'){removeCard(d,'TACKLE');addFlow(`${name(d)} TACKLE PASS`,'good');const passer=from;if(has(passer,'YELLOW')&&Math.random()<.35){removeCard(passer,'YELLOW');addFlow('AI YELLOW → TACKLE','bad');state.ball=to;render();setTimeout(aiChooseAction,400)}else{state.ball=d;state.phase='play';state.busy=false;state.selectedHand=d;setNotice('Pass intercepted. Your team has Soccer.');render();afterResolution()}}else{state.ball=to;render();setTimeout(aiChooseAction,450)}})}else{state.ball=to;render();setTimeout(aiChooseAction,450)}}
function offerTrackBackIfNeeded(team,cb){const missing=state.counterMissing[team];if(!missing){cb();return}if(team==='blue'&&state.hands[missing].length){showModal('COUNTERATTACK',`${name(missing)} shot and was caught out of position. Discard 1 card to recover the missing defensive line?`,[['TRACK BACK','yes'],['STAY FORWARD','no']],v=>{if(v==='yes')showModal('DISCARD 1',`Choose a card from ${name(missing)} to spend on the recovery run.`,[...new Set(state.hands[missing])].map(c=>[`DISCARD ${c}`,c]),c=>{removeCard(missing,c);state.counterMissing[team]=null;addFlow(`${name(missing)} TRACKS BACK`,'good');cb()});else cb()})}else if(team==='green'&&state.hands[missing].length&&Math.random()<.55){const c=randomDiscard(missing);state.counterMissing[team]=null;addFlow(`${name(missing)} DISCARD ${c} · TRACK BACK`,'bad');cb()}else cb()}
function afterResolution(){if(state.timeExpired&&!state.attack){finishMatch('FULL TIME');return}checkDeadGame()}
function checkDeadGame(){if(state.ended)return;const blueCards=BLUE.reduce((n,id)=>n+state.hands[id].length,0),greenCards=GREEN.reduce((n,id)=>n+state.hands[id].length,0);if(blueCards===0&&greenCards===0){finishMatch('NO CARDS LEFT');return}const blueShoot=BLUE.some(id=>has(id,'SHOOT')),greenShoot=GREEN.some(id=>has(id,'SHOOT'));if(!blueShoot&&!greenShoot&&state.phase!=='trade'&&state.phase!=='rps'){finishMatch('NO LEGAL ATTACKS')}}
function finishMatch(reason){if(state.ended)return;state.ended=true;clearInterval(state.timer);state.phase='ended';state.busy=true;state.attack=null;setNotice(`${reason}. FINAL SCORE: BLUE ${state.score.blue} — ${state.score.green} GREEN.`);log(`Match ends: ${reason}.`);render();if(state.score.blue===state.score.green)setTimeout(penaltyShootout,500);else showModal('FULL TIME',`${state.score.blue>state.score.green?'BLUE':'GREEN'} wins ${Math.max(state.score.blue,state.score.green)}–${Math.min(state.score.blue,state.score.green)}.`,[['PLAY AGAIN','again'],['MATCH MENU','menu']],v=>{if(v==='again')location.reload();else location.href='match.html'})}
function penaltyShootout(){let round=1;const run=()=>{const deck=shuffle(FULL_DECK);const draws={B1:deck.pop(),B2:deck.pop(),BKG:deck.pop(),G1:deck.pop(),G2:deck.pop(),GKG:deck.pop()};const blueShots=['B1','B2'].reduce((n,id)=>n+(draws[id]==='SHOOT'?1:0),0),greenShots=['G1','G2'].reduce((n,id)=>n+(draws[id]==='SHOOT'?1:0),0);const blueSave=draws.BKG==='DEFENSE'?1:0,greenSave=draws.GKG==='DEFENSE'?1:0;const bs=blueShots-greenSave,gs=greenShots-blueSave;const html=`<div class="penGrid"><div class="penCard"><b>BLUE</b><br>${BLUE.map(id=>`${name(id)}: ${draws[id]} ${!isGK(id)&&draws[id]==='SHOOT'?'(+1)':isGK(id)&&draws[id]==='DEFENSE'?'(-1 to GREEN)':''}`).join('<br>')}<br><b>TEAM SCORE ${bs}</b></div><div class="penCard"><b>GREEN</b><br>${GREEN.map(id=>`${name(id)}: ${draws[id]} ${!isGK(id)&&draws[id]==='SHOOT'?'(+1)':isGK(id)&&draws[id]==='DEFENSE'?'(-1 to BLUE)':''}`).join('<br>')}<br><b>TEAM SCORE ${gs}</b></div></div>`;showModal(`PENALTY SHOOTOUT · DRAW ${round}`,`All Action Cards were reshuffled. Each Player scores +1 only on SHOOT. A Goalkeeper who draws DEFENSE subtracts 1 from the other team.${html}`,[['CONTINUE','go']],()=>{if(bs===gs){round++;run()}else showModal('MATCH WINNER',`${bs>gs?'BLUE':'GREEN'} wins the penalty shootout, ${Math.max(bs,gs)} to ${Math.min(bs,gs)}.`,[['PLAY AGAIN','again'],['MATCH MENU','menu']],v=>{if(v==='again')location.reload();else location.href='match.html'})})};run()}
function showModal(title,text,opts,cb){const m=$('modal');$('modalTitle').textContent=title;$('modalText').innerHTML=text;$('modalActions').innerHTML='';opts.forEach(([label,val])=>{const b=document.createElement('button');b.className='action'+(String(label).includes('YELLOW')?' yellow':'');b.textContent=label;b.onclick=()=>{m.classList.remove('on');cb(val)};$('modalActions').appendChild(b)});m.classList.add('on')}
deal();
})();
