create table if not exists public.gsm_events (
  id bigint generated by default as identity primary key,
  site text not null default 'goal-scoring-moment',
  visitor_id text not null,
  session_id text not null,
  event_name text not null,
  event_label text,
  page_path text,
  page_title text,
  mode text,
  active_seconds integer not null default 0,
  device_type text,
  referrer_host text,
  meta jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists gsm_events_occurred_at_idx on public.gsm_events (occurred_at desc);
create index if not exists gsm_events_session_id_idx on public.gsm_events (session_id);
create index if not exists gsm_events_visitor_id_idx on public.gsm_events (visitor_id);
create index if not exists gsm_events_event_name_idx on public.gsm_events (event_name);
create index if not exists gsm_events_mode_idx on public.gsm_events (mode);

alter table public.gsm_events enable row level security;

-- Website visitors may insert analytics rows using the public anon key.
drop policy if exists "gsm public insert" on public.gsm_events;
create policy "gsm public insert"
on public.gsm_events
for insert
to anon
with check (
  site = 'goal-scoring-moment'
  and char_length(visitor_id) between 8 and 120
  and char_length(session_id) between 8 and 120
  and event_name in ('page_view','session_start','session_end','heartbeat','interaction','mode_selected','tutorial_started','tutorial_completed')
  and active_seconds between 0 and 86400
);

-- Dashboard currently reads with the anon key. Keep this only if the dashboard URL is private/unlinked.
-- For stronger privacy, replace this with authenticated dashboard access later.
drop policy if exists "gsm dashboard read" on public.gsm_events;
create policy "gsm dashboard read"
on public.gsm_events
for select
to anon
using (site = 'goal-scoring-moment');

revoke update, delete on table public.gsm_events from anon;
grant insert, select on table public.gsm_events to anon;
